# Generated by Django 5.2.5 on 2025-08-24 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local Model'), ('custom', 'Custom API')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=500)),
                ('api_base_url', models.URLField(blank=True)),
                ('settings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(blank=True, null=True)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('cost_per_1k_tokens', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'db_table': 'llm_integration_llm_model',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMProcessingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_size', models.PositiveIntegerField(default=1000)),
                ('overlap_size', models.PositiveIntegerField(default=100)),
                ('max_tokens', models.PositiveIntegerField(default=4000)),
                ('confidence_threshold', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('entity_types', models.JSONField(default=list)),
                ('prompt_type', models.CharField(choices=[('general_ner', 'General NER'), ('urdu_ner', 'Urdu NER'), ('marsiya_ner', 'Marsiya NER'), ('custom', 'Custom')], default='marsiya_ner', max_length=20)),
                ('custom_prompt', models.TextField(blank=True)),
                ('custom_entity_types', models.JSONField(default=list)),
                ('custom_instructions', models.TextField(blank=True)),
                ('enable_post_processing', models.BooleanField(default=True)),
                ('enable_entity_validation', models.BooleanField(default=True)),
                ('enable_confidence_scoring', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LLM Processing Config',
                'verbose_name_plural': 'LLM Processing Configs',
                'db_table': 'llm_integration_llm_processing_config',
                'ordering': ['name'],
            },
        ),
    ]
