# Generated by Django 5.2.5 on 2025-08-24 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmprocessingconfig',
            name='llm_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_configs', to='llm_integration.llmmodel'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['name'], name='llm_integra_name_022bed_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['provider'], name='llm_integra_provide_40b5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['is_active'], name='llm_integra_is_acti_4e4b32_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['priority'], name='llm_integra_priorit_d74c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['is_default'], name='llm_integra_is_defa_cd6cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprocessingconfig',
            index=models.Index(fields=['llm_model'], name='llm_integra_llm_mod_237adf_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprocessingconfig',
            index=models.Index(fields=['prompt_type'], name='llm_integra_prompt__755f79_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprocessingconfig',
            index=models.Index(fields=['is_active'], name='llm_integra_is_acti_c869da_idx'),
        ),
    ]
