# Generated by Django 5.2.5 on 2025-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('research_area', models.CharField(blank=True, max_length=200)),
                ('methodology', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list)),
                ('timeline', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('allow_public_view', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('researcher', 'Researcher'), ('viewer', 'Viewer')], default='researcher', max_length=20)),
                ('can_edit_project', models.BooleanField(default=False)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_upload_documents', models.BooleanField(default=True)),
                ('can_edit_entities', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Project Membership',
                'verbose_name_plural': 'Project Memberships',
                'db_table': 'projects_project_membership',
            },
        ),
    ]
