# Generated by Django 5.2.5 on 2025-08-24 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('ner_processing', 'NER Processing'), ('entity_verification', 'Entity Verification'), ('document_analysis', 'Document Analysis'), ('export_generation', 'Export Generation'), ('email_sending', 'Email Sending'), ('data_import', 'Data Import'), ('cleanup', 'Cleanup'), ('custom', 'Custom')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('memory_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('priority', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Processing Job',
                'verbose_name_plural': 'Processing Jobs',
                'db_table': 'processing_processing_job',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
