# Generated by Django 5.2.5 on 2025-08-24 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(db_index=True, max_length=500)),
                ('start_position', models.PositiveIntegerField()),
                ('end_position', models.PositiveIntegerField()),
                ('line_number', models.PositiveIntegerField()),
                ('word_position', models.PositiveIntegerField()),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('quality_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('llm', 'LLM'), ('manual', 'Manual'), ('import', 'Import'), ('correction', 'Correction')], default='llm', max_length=20)),
                ('context_before', models.CharField(blank=True, max_length=200)),
                ('context_after', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('attributes', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'db_table': 'entities_entity',
            },
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('same_as', 'Same As'), ('part_of', 'Part Of'), ('contains', 'Contains'), ('located_in', 'Located In'), ('works_for', 'Works For'), ('married_to', 'Married To'), ('parent_of', 'Parent Of'), ('child_of', 'Child Of'), ('sibling_of', 'Sibling Of'), ('mentions', 'Mentions'), ('references', 'References'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entity Relationship',
                'verbose_name_plural': 'Entity Relationships',
                'db_table': 'entities_entity_relationship',
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color_code', models.CharField(help_text='Hex color code (e.g., #87CEEB)', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('validation_rules', models.JSONField(default=dict)),
                ('examples', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity Type',
                'verbose_name_plural': 'Entity Types',
                'db_table': 'entities_entity_type',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
