# Generated by Django 5.2.5 on 2025-08-24 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='documents.document'),
        ),
        migrations.AddField(
            model_name='entity',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entityrelationship',
            name='source_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='entityrelationship',
            name='target_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='related_entities',
            field=models.ManyToManyField(related_name='related_to', through='entities.EntityRelationship', to='entities.entity'),
        ),
        migrations.AddIndex(
            model_name='entitytype',
            index=models.Index(fields=['name'], name='entities_en_name_9d0d39_idx'),
        ),
        migrations.AddIndex(
            model_name='entitytype',
            index=models.Index(fields=['is_active'], name='entities_en_is_acti_9c4206_idx'),
        ),
        migrations.AddIndex(
            model_name='entitytype',
            index=models.Index(fields=['sort_order'], name='entities_en_sort_or_88c6c7_idx'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='entities.entitytype'),
        ),
        migrations.AddIndex(
            model_name='entityrelationship',
            index=models.Index(fields=['source_entity', 'target_entity'], name='entities_en_source__cf86d8_idx'),
        ),
        migrations.AddIndex(
            model_name='entityrelationship',
            index=models.Index(fields=['relationship_type'], name='entities_en_relatio_002876_idx'),
        ),
        migrations.AddIndex(
            model_name='entityrelationship',
            index=models.Index(fields=['is_verified'], name='entities_en_is_veri_147d5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entityrelationship',
            unique_together={('source_entity', 'target_entity', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['text'], name='entities_en_text_13e0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_type'], name='entities_en_entity__67056b_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['document'], name='entities_en_documen_ab6767_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['start_position', 'end_position'], name='entities_en_start_p_80a3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['line_number'], name='entities_en_line_nu_1200f2_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_verified'], name='entities_en_is_veri_13e7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['confidence_score'], name='entities_en_confide_5bbc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['source'], name='entities_en_source_01ec43_idx'),
        ),
    ]
