# Generated by Django 5.2.5 on 2025-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('login', 'Login'), ('logout', 'Logout'), ('process', 'Process'), ('verify', 'Verify')], max_length=20)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'audit_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
